# Generated by Django 4.2.6 on 2024-04-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasktodo', '0003_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
