# Generated by Django 4.2.7 on 2024-04-14 16:41

from django.db import migrations, models
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tasktodo', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-publish']},
        ),
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='task_image/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='task',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['-publish'], name='tasktodo_ta_publish_b65f71_idx'),
        ),
    ]
