# Generated by Django 4.2.6 on 2024-04-21 01:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasktodo', '0008_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='users_like',
            field=models.ManyToManyField(null=True, related_name='images_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
