# Generated by Django 4.2.6 on 2024-04-21 01:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasktodo', '0013_rename_like_like_task_alter_like_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='users_like',
            field=models.ManyToManyField(related_name='user_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
